version: '3.6'
services:
  db:
    container_name: db
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_PASSWORD: ${PG_PASSWORD}
      POSTGRES_USER: ${PG_USER}
      POSTGRES_HOST_AUTH_METHOD: trust
    image: 'postgres:11-alpine'
    restart: always
    ports:
      - '5433:5433'
    volumes:
      - 'pgdata:/var/lib/postgresql/data'
  api:
    container_name: api
    environment:
      MIX_ENV: dev
      PG_USER: ${PG_USER}
      PG_PASSWORD: ${PG_PASSWORD}
      PG_DB: ${PG_DB}
      PG_HOSTNAME: ${PG_HOSTNAME}
    build: ./timemanager_api
    depends_on:
      - db
    ports:
      - '4000:4000'
  front:
    container_name: Front_container
    build: 
      context: ./front/
    environment:
      NODE_ENV: development2
    ports:
      - '80:8080'
volumes:
  pgdata: 