version: '3.6'
services:
  db:
    container_name: DB_Postgresql
    env_file:
      - db.env
    image: 'postgres:11-alpine'
    restart: always
    ports:
      - '5433:5433'
    volumes:
      - 'pgdata:/var/lib/postgresql/data'
  api:
    container_name: API_container
    env_file:
      - api.env
    build: 
      context: ./timemanager_api/
    depends_on:
      - db
    environment:
      MIX_ENV: dev
    env_file:
      - api.env
    ports:
      - '4000:4000'
  front:
    container_name: Front_container
    build: 
      context: ./front/
    depends_on:
      - api
    environment:
      MIX_ENV: dev
    ports:
      - '8080:8080'
volumes:
  pgdata: {}