
version: 2

jobs:    
  build:
    docker:
      - image: circleci/elixir:latest
        environment:
          MIX_ENV: test
            
      - image: circleci/postgres:latest
        environment:
          POSTGRES_PASSWORD: postgres
          POSTGRES_USER: postgres
          POSTGRES_HOST_AUTH_METHOD: trust

    working_directory: ~/repo/timemanager_api
    steps:
      - checkout:
          path: ~/repo
      - run: mix local.hex --force
      - run: mix deps.compile
      - run: mix local.rebar --force 
      - run: mix deps.get --force 
      - run: mix ecto.create 
      - run: mix ecto.migrate
      - run: mix test   
  node:
    docker:
      - image: cimg/node:16.13.0-browsers

    working_directory: ~/repo/front

    steps:
      - checkout:
          path: ~/repo
      - run: npm install && npm run lint
      - run: npm install && npm run build

  deploy-job:
    docker:
      - image: cimg/node:16.13.0-browsers
    steps:
      - add_ssh_keys:
          fingerprints:
            - "28:89:9f:3b:5f:f7:7a:55:29:01:cb:1b:10:5f:3b:92"
      - run: ssh -o "StrictHostKeyChecking no" circleci@ligne7.pepintrie.fr ls
workflows:
  version: 2
  build_and_test:
    jobs:
      - deploy-job